### ISSUE TITLE
Conda Issue

### ISSUE THREAD

**Issue by italhaali** [ViRGIS-Team/gdal-upm#20]
The type or namespace name 'Conda' could not be found (are you missing a using directive or an assembly reference?)

**Comment by runette** [comment]
Could you add more information

**Comment by italhaali** [comment]
Yes, when i integrated the package i got the error
This type of namespace Conda does not exist in current Context.
I integrated package twice but same error.
May be some Conda class missing or some library

**Comment by runette** [comment]
The Conda class comes from the dependency package CondaExtensions.

Your error message would say that this package is not being loaded. 

Can I ask how you are installing the package? Is it through OpenUPM or GH and have you added the scoped registries as per the readme?

Thanks

**Comment by italhaali** [comment]
I did it through git hub 
I downloaded zip and then dragged folder in unity

**Comment by runette** [comment]
If you do that - you do not get the dependencies.

This is a Unity Package Manager package - it is designed to be installed through the Unity Package Manager.

However - if that is the way you prefer to work then you also need to do the same thing for [Conda-Extensions](https://github.com/ViRGIS-Team/CondaExtensions)

**Comment by italhaali** [comment]
Thank you its working
