### ISSUE TITLE
DllNotFoundException for gdal_wrap in Unity with GDAL Package

### ISSUE THREAD

**Issue by bensasl2** [ViRGIS-Team/gdal-upm#24]
**Environment:**
- Unity version: [2022.3.16f1]
- Operating System: [Windows 11]
- Visual Studio version [Visual Studio 2022]

**Issue Description:**
I am encountering a `DllNotFoundException` when trying to use the GDAL package in Unity. The specific error is for `gdal_wrap`. This issue arises when attempting to initialize GDAL using `Gdal.AllRegister();` in a C# script.

**Error Message:**
DllNotFoundException: gdal_wrap assembly:<unknown assembly> type:<unknown type> member:(null)
OSGeo.GDAL.GdalPINVOKE+SWIGExceptionHelper..cctor () (at ./Library/PackageCache/com.virgis.gdal@e85ead4664/Runtime/Scripts/gdal/GdalPINVOKE.cs:139)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
OSGeo.GDAL.GdalPINVOKE..cctor () (at ./Library/PackageCache/com.virgis.gdal@e85ead4664/Runtime/Scripts/gdal/GdalPINVOKE.cs:159)
Rethrow as TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
OSGeo.GDAL.Gdal.AllRegister () (at ./Library/PackageCache/com.virgis.gdal@e85ead4664/Runtime/Scripts/gdal/Gdal.cs:861)
S57Reader.Start () (at Assets/myscript.cs:10)

**Steps to Reproduce:**
1. Installed the GDAL package in Unity via Unity Package Manager and the git link after adding scopedRegistries to manifest.json.
2. Created a C# script to utilize GDAL functionalities.
3. Encountered the error upon running the Unity scene with the script.

I would appreciate any guidance or suggestions to resolve this issue. Thank you!

**Comment by bensasl2** [comment]
Update: Issue Resolved

I wanted to provide an update on this issue. After further investigation, I discovered that the problem was related to the Conda installation. Once I addressed the Conda setup, the DllNotFoundException for gdal_wrap was resolved.

**Comment by runette** [comment]
Thanks for the issue and the update. I was about to say that this issue is almost certainly due to the conda configuration.

Using Conda does introduce some complexity - but it solves even more problems with dependencies with GDAL and with updates so it is worth it :)

Thanks for using the package
