### ISSUE TITLE
Add a reference to assembly netstandard 2.0

### ISSUE THREAD

**Issue by slanoe** [ViRGIS-Team/gdal-upm#8]
Hello,
I have 24 errors like this when I want to build: 

```
Library\PackageCache\com.virgis.gdal@3.4.100\Runtime\Scripts\GdalConfiguration.cs(57,22): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

I use Unity 2018.4.17f1. I want to build a Universal Windows Platform. I select Scripting Runtime Version .NET 4.x Equivalent / Scripting Backend .NET / Api Compatibility Level .NET Standadard 2.0

**Comment by runette** [comment]
@slanoe I have created a HIGHLY EXPERIMENTAL version using a new approach that MAY :

- Work with .NET as described in your config - as I said I will not have access to a Windows machine to test UWP builds until next week. It works with Mono. It would be good if you can try it and see what results you get ...

- Is working in very initial tests (on Mac at the moment) with IL2CPP. If you cannot get it working with .NET you could try with IL2CPP. As I say - the tests have only been preliminary - so I am fairly sure there will be some error messages.

To use this EXPERIMENTAL version - go to `Package Manager` and `Install from Git Url` and use the following Url

```
https://github.com/ViRGIS-Team/gdal-upm.git#change-to-swig-scripts
```

This is a change in the UPM package / C# and does not involve any change to the Conda / CPP package - so that should not need to be touched (i.e. the update should not take long - although there will be a fair amount of 'Compiling C# scripts" ... :)

**Comment by slanoe** [comment]
Hello,
Thank you for your quick response.
I can't select a git url in Unity version 2018.4.17f1. I have modified directly in the manifest.json:

```
    "com.virgis.gdal": "https://github.com/ViRGIS-Team/gdal-upm.git#change-to-swig-scripts",
```

I created a new project with only an empty 3D scene and gdal-upm.

I have many errors like this with same configuration Scripting Runtime Version `.NET 4.x Equivalent` / Scripting Backend `.NET` / Api Compatibility Level `.NET Standadard 2.0`:

```
Library\PackageCache\com.virgis.gdal@01fa2c141dd73601593922f0887c2ffa1678341e\Runtime\Scripts\osr\CoordinateTransformation.cs(30,17): error CS0246: The type or namespace name 'HandleRef' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.virgis.gdal@01fa2c141dd73601593922f0887c2ffa1678341e\Runtime\Scripts\osr\AreaOfUse.cs(30,17): error CS0246: The type or namespace name 'HandleRef' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.virgis.gdal@01fa2c141dd73601593922f0887c2ffa1678341e\Runtime\Scripts\ogr\AreaOfUse.cs(30,17): error CS0246: The type or namespace name 'HandleRef' could not be found (are you missing a using directive or an assembly reference?)
...
```

**Comment by runette** [comment]
On Sat, 12 Feb 2022, 06:23 slanoe, ***@***.***> wrote:

> Hello,
> Thank you for your quick response.
> I can't select a git url in Unity version 2018.4.17f1.
>
Just a question - is there any reason you area using such an old version?


I can check on Monday - but an update to 2020 or 2021 might help - just by
increasing the API support levels. They are also just generally much better
product and much more reliable.

> I have modified directly in the manifest.json:
>
>     "com.virgis.gdal": "https://github.com/ViRGIS-Team/gdal-upm.git#change-to-swig-scripts",
>
> I created a new project with only an empty 3D scene and gdal-upm.
>
> I have many errors like this with same configuration Scripting Runtime
> Version .NET 4.x Equivalent / Scripting Backend .NET / Api Compatibility
> Level .NET Standadard 2.0:
>
> ***@***.***\Runtime\Scripts\osr\CoordinateTransformation.cs(30,17): error CS0246: The type or namespace name 'HandleRef' could not be found (are you missing a using directive or an assembly reference?)
> ***@***.***\Runtime\Scripts\osr\AreaOfUse.cs(30,17): error CS0246: The type or namespace name 'HandleRef' could not be found (are you missing a using directive or an assembly reference?)
> ***@***.***\Runtime\Scripts\ogr\AreaOfUse.cs(30,17): error CS0246: The type or namespace name 'HandleRef' could not be found (are you missing a using directive or an assembly reference?)
> ...
>
>
Ok. This means that this configuration does not support
System.Runtime.InteropServices. If that is true, then GDAL is never going
to work with this config.

Can you try using the IL2CPP accepting backend as suggested by the Unity
support ticket I copied in the previous comment. It is probably the best
long term solution.

If you are doing that - it would be good to move to 2020.3 or 2021.x -
Unity have made a lot of improvements to the AOT in the latter versions.

**Comment by runette** [comment]
This seems to explain the problem ...

https://github.com/swig/swig/issues/455

It looks like GDAL would have to change the entire basis of their SWIG
scripts to make this work - many thousands of lines of code and also used
for the Python and Java bindings!

Looks like IL2CPP is the only way to go for UWP!
