### ISSUE TITLE
Cannot find install_script.ps1

### ISSUE THREAD

**Issue by runette** [ViRGIS-Team/gdal-upm#9]
see https://github.com/ViRGIS-Team/CondaExtensions/issues/4

**Comment by runette** [comment]
I am trying to understand the background to the first error message - when do you get this message? It looks like there should be more to the error message with the Unity Editor details about when it was called?

Do you have the full error log?

**Comment by runette** [comment]
@slanoe - I could do with some more information on this

**Comment by runette** [comment]
Do you think that you could PR  that change for me? I am actually in the field at the moment and wont be able to get to it for about 4 weeks - but it would be good record your fix in a PR and that will make it easier for me to review it when I get back.

**Comment by Reddevildragg** [comment]
Have created a PR in the conda extensions package where i believe the fault was https://github.com/ViRGIS-Team/CondaExtensions/pull/5 as a link.

**Comment by runette** [comment]
Thanks - this is released in Conda Extensions 1.0.3 and should be in use soon

**Comment by runette** [comment]
Released in version 3.4.300
